export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'

export const CHANGE_HOT_RECOMMENDS = 'CHANGE_HOT_RECOMMENDS'

export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS'

export const CHANGE_TOP_SONG_RANK = 'CHANGE_TOP_SONG_RANK'

export const CHANGE_NEW_SONG_RANK = 'CHANGE_NEW_SONG_RANK'

export const CHANGE_ORIGINAL_SONG_RANK = 'CHANGE_ORIGINAL_SONG_RANK'

export const ID_TOP_SONG_RANK = 19723756
export const ID_NEW_SONG_RANK = 3779629
export const ID_ORIGINAL_SONG_RANK = 2884035
