export const CHANGE_CUR_SONG_DETAIL = 'CHANGE_CUR_SONG_DETAIL'

export const CHANGE_CUR_SONG_INDEX = 'CHANGE_CUR_SONG_INDEX'

export const CHANGE_PLAYLIST = 'CHANGE_PLAYLIST'

export const CHANGE_PLAYMODE = 'CHANGE_PLAYMODE'